### ISSUE TITLE
pytorch support for A100 sm_80 

### ISSUE THREAD

**Issue by sung** [andreimargeloiu/WPFS#3]
I've got the following error message while running `run_experiment.sh`:
```code
NVIDIA A100-SXM4-80GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
```

I was wondering whether the current pyTorch version (v1.10.1) from the `requirements.txt` supports sm_80 or not?

**Comment by sung** [comment]
I found the following two lines should be modified from `requirements.tx` to sort this issue out:
```code
torch==1.10.1+cu111
torchvision==0.11.2+cu111
```

**Comment by andreimargeloiu** [comment]
I'm glad the issue is fixed!
